### ISSUE TITLE
The JavaScriptSerializer is your friend

### ISSUE THREAD

**Issue by jswindell** [mcammarato/dashboard#1]
Consider using the JavaScriptSerializer class for the UploadString() call:

![image](https://cloud.githubusercontent.com/assets/722549/25257672/8fef1a00-2607-11e7-9ae4-0925b4d431b8.png)

**Comment by mcammarato** [comment]
That variable has been updated to use the serializer, much better approach than what I was doing before. The next issue I have to fix is shaping the pocket response in the mode, currently it does not work.
